Add speakers' information
OpnTec/vn.opentechsummit.asia pull request #51
Opened 2019-12-08 18:39 UTC by huonggiangbui

Personal Information about: Eden Dang, Clif Kussmaul, Barend Scholtus

- [ ] Included a Preview link and screenshot showing after and before the changes.
- [ ] Included a description of the change below.
- [ ] Squashed the commits.

# Changes done in this Pull Request
Add icons relate to personal information of speakers

![image](https://user-images.githubusercontent.com/51595094/70394124-6b537d80-1a24-11ea-9494-07c0d2619de4.png)
![image](https://user-images.githubusercontent.com/51595094/70394127-7c03f380-1a24-11ea-9441-c31e0d45b4e8.png)

![image](https://user-images.githubusercontent.com/51595094/70394133-87efb580-1a24-11ea-95ec-f452ab89002c.png)
![image](https://user-images.githubusercontent.com/51595094/70394134-9211b400-1a24-11ea-891a-57125ce4e930.png)

![image](https://user-images.githubusercontent.com/51595094/70394139-9b028580-1a24-11ea-8d94-87b02faf677d.png)
![Uploading image.png…]()

- [Preview Link](https://huonggiangbui.github.io/vn.opentechsummit.asia/)

- Fixes #49

2019-12-08 19:06 UTC, nikit19 approved these changes

2019-12-08 19:07 UTC, nikit19 commented
Looks good but it would be nice if you could indent the code

2019-12-08 21:11 UTC, mariobehling requested changes
Please take out "?lang=en" from links, e.g. here: https://twitter.com/kussmaul?lang=en

2019-12-12 06:40 UTC, huonggiangbui commented
> Please take out "?lang=en" from links, e.g. here: https://twitter.com/kussmaul?lang=en



> Please take out "?lang=en" from links, e.g. here: https://twitter.com/kussmaul?lang=en

I fixed it. Please check

2019-12-12 18:08 UTC, merged