Add social links to some speakers
OpnTec/vn.opentechsummit.asia pull request #52
Opened 2019-12-12 15:29 UTC by MuhammadWasif

Adding social links to the profile of **Barend Scholtus**, **Bien Nguyen**, **Nam Phuong Nguyen Luong**, **Clif Kussmail**, **Eden Dang** and **Vu The Binh**
Here's the deployment link:
https://wasif.codes/vn.opentechsummit.asia/

2019-12-12 18:08 UTC, mariobehling commented
Thanks. Please resolve conflicts.

2019-12-13 14:33 UTC, MuhammadWasif commented
@mariobehling , conflicts have been resolved. Please check now

2019-12-13 14:39 UTC, mariobehling commented on index.html
> -				<a href="https://www.facebook.com/ckussmaul"><i class="icon social_facebook"></i></a>
Already added

2019-12-13 14:39 UTC, mariobehling commented on index.html
> -			<div class="social-links vertical-align">
Already added

2019-12-13 14:39 UTC, mariobehling commented on index.html
> +                                <a href="https://www.facebook.com/ckussmaul"><i class="icon fa fa-facebook"></i></a>
Linkedin and Twitter are already added

2019-12-13 14:40 UTC, mariobehling requested changes
Please go through your code. Only add people ones. Some links are there already.

2019-12-13 15:26 UTC, MuhammadWasif commented
Fixed issues and added links for some more speakers

2019-12-13 16:01 UTC, mariobehling approved these changes

2019-12-13 16:01 UTC, merged