Add Social Profile
OpnTec/vn.opentechsummit.asia pull request #64
Opened 2020-01-09 16:14 UTC by hoangdatngo

This is the work for this issue: #63 

I have added links to various social profile of some of the speakers in the Fossasia OpenTechSummit Vietnam.

The deployment link: https://hoangdatngo.github.io/vn.opentechsummit.asia/

@mariobehling, @kushthedude, @hpdang Can any mentor please review my PR?

2020-01-11 14:48 UTC, hoangdatngo commented
@liveHarshit, @kushthedude, @mariobehling Can any mentor please review this. I have been waiting for 2 days.

2020-01-11 14:51 UTC, kushthedude approved these changes
Looks good

2020-01-12 01:32 UTC, hoangdatngo commented
@kushthedude Can you please merge my PR?

2020-01-12 01:35 UTC, kushthedude commented
Actually I dont have merge rights for this repository.
@mariobehling @hpdang Please check and merge it.

On Sun, 12 Jan, 2020, 07:02 Dat, <notifications@github.com> wrote:

> @kushthedude <https://github.com/kushthedude> Can you please merge my PR?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpnTec/vn.opentechsummit.asia/pull/64?email_source=notifications&email_token=AKQMTLVKYEAZUG7HRRTBINTQ5JXJJA5CNFSM4KE23IK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIWPIGQ#issuecomment-573371418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKQMTLS5R7OJ3PHKAVKC2T3Q5JXJJANCNFSM4KE23IKQ>
> .
>

2020-01-12 01:48 UTC, hoangdatngo commented
@kushthedude ok, thanks. You review so fast!

2020-01-12 06:13 UTC, cweitat requested changes

2020-01-12 06:13 UTC, cweitat commented on index.html
> +				<a href="https://www.instagram.com/barend.scholtus/"><i class="icon fa fa-instagram"></i></a>
follow the indent

2020-01-12 06:13 UTC, cweitat commented on index.html
> +				<a href="https://www.flickr.com/photos/rportrr/"><i class="icon fa fa-flickr"></i></a>
what is this? how is it relevant?

2020-01-12 06:13 UTC, cweitat commented on index.html
> +				<a href="https://blog.ffii.org/author/mariobehling/" target="_self"><i class="icon fa fa-external-link"></i></a>
how is link that is updated at 2015 useful?

2020-01-12 06:13 UTC, cweitat commented on index.html
> +				<a href="https://www.youtube.com/user/mariobehling" target="default"><i class="icon social_youtube"></i></a>
how is the channel useful in telling the profile of person??

2020-01-12 06:13 UTC, cweitat commented on index.html
> +					</div>
follow the indent

2020-01-12 06:13 UTC, cweitat commented on index.html
> +					</div>
follow the indent

2020-01-12 06:13 UTC, cweitat commented on index.html
> +				<a href="https://www.linkedin.com/in/f%C3%A9lix-becquart-8a5a46a6/"><i class="icon social_linkedin"></i></a>
follow the indent

2020-01-15 16:50 UTC, closed without merging